### ISSUE TITLE
Could you share the rosbag for the VELODYNE 3D lidar again?

### ISSUE THREAD

**Issue by Yadong-wong** [SohaibAl-emara/3D_Lidar_Curb_Detection#1]
I found that the rosbag couldn't download from your click,is this because your link is broken? I will be grateful to you if you can share the rosbag again,thank you!

**Comment by SohaibAl-emara** [comment]
try this 
```
wget https://autoware-ai.s3.us-east-2.amazonaws.com/sample_moriyama_data.tar.gz
```
